//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblNotasEstudiante
    {
        public int id { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> lab1 { get; set; }
        public Nullable<double> lab2 { get; set; }
        public Nullable<double> lab3 { get; set; }
        public Nullable<double> par1 { get; set; }
        public Nullable<double> par2 { get; set; }
        public Nullable<double> par3 { get; set; }
    }
}
